app.py
from flask import Flask

def create_app():

    app = Flask(__name__)

    from .blueprints.user import user
    app.register_blueprint(user)

    from .blueprints.api import api
    app.register_blueprint(api)

    return app

blueprints/api.py
import csv
import json
import requests
from flask import Blueprint, render_template, request, url_for, send_from_directory

api = Blueprint('api', __name__)

@api.route('/get-earthquakes', methods=['GET', 'POST'])
def post_results():

    if request.method == 'POST':

        duration = request.form["duration"]
        response = requests.get(f"https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/{duration}.geojson")

        data = json.loads(response.text)
        results = []

        for d in data["features"]:
            if 'CA' in d["properties"]["place"]:
                results.append({"mag": d["properties"]["mag"], "place": d["properties"]["place"], "url": d["properties"]["url"]})

            with open('csv/eq.csv', 'w', newline='') as csvfile:
                csvwriter = csv.writer(csvfile, delimiter = ',')
                csvwriter.writerow(["Magnitude", "Location", "URL"])
                for r in results:
                    csvwriter.writerow([r["mag"], r["place"], r["url"]])

        return render_template('results.html', results=results)

blueprints/user.py
from flask import Blueprint, render_template, send_from_directory

user = Blueprint('user', __name__)

@user.route('/')
@user.route('/home')
def home():
    return render_template('index.html')

@user.route('/csv-download', methods=['GET', 'POST'])
def csv():
    return send_from_directory('csv', 'eq.csv', mimetype='text/csv', attachment_filename='eq.csv',as_attachment=True)

templates/includes/_footer.html
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

templates/index.html
{% extends 'layout.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-lg-6 offset-3">
            <br>
            <form method="POST" action="{{ url_for('api.post_results') }}">
                <div class="text-center mb-4">
                    <h1 class="h3 mb-3 font-weight-normal">Locate Earthquakes!</h1>
                    <p>Select an option from the dropdown menu and click Get Data below!</p>
                  </div>
              
                  <div class="form-label-group text-center">
                      <select class="form-control" name="duration">
                          <option value="">-- Select --</option>
                          <option value="all_hour">1 Hour</option>
                          <option value="all_day">1 Day</option>
                      </select>

                      <hr>
                  </div>
                  <button class="btn btn-lg btn-info btn-block" type="submit">Get Data</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

{% include 'includes/_header.html' %}

      {% block body %}

        

      {% endblock %}

  {% include 'includes/_footer.html' %}

templates/results.html
{% extends 'layout.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 offset-2">
            <br>
            <a class="btn btn-sm btn-info float-right" href="{{ url_for('user.csv', filename=filename)}}">Download CSV</a>
            <br>
            <br>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">Magnitude</th>
                        <th scope="col">Location</th>
                        <th scope="col">Details</th>
                    </tr>
                    </thead>
                    {% for r in results %}
                    <tbody>
                    <tr>
                        <td>{{ r.mag }}</td>
                        <td>{{ r.place }}</td>
                        <td><a href="{{r.url}}" target="_blank">Details</a></td>
                    </tr>
                    </tbody>
                    {% endfor %}
                </table>
                <br>
                <hr>
{% endblock %}